# -----------------------------------------------------
# Animations
# name "Default"
# credit https://github.com/mylinuxforwork/dotfiles
# -----------------------------------------------------
animations {
    enabled = false
}
