# --- Monitor ---
source = ./conf/monitor.conf

# --- Cursor ---
source = ./conf/cursor.conf

# --- Keybinds ---
source = ./conf/keybinds.conf

# --- Autostart ---
source = ./conf/autostart.conf

# --- Input ---
source = ./conf/input.conf

# --- Animations ---
source = ./conf/animation.conf

# --- Decoration ---
source = ./conf/decoration.conf

# --- Window rules ---
source = ./conf/windowrules.conf

# --- Workspace rules ---
source = ./conf/workspacerules.conf

# --- Load Noctalia colors ---
source = ./noctalia/noctalia-colors.conf

# --- Environment ---
source = ./conf/env.conf

# --- System ---
source = ./conf/system.conf
