# --- Startup programs ---
# Shell
exec-once = qs -c noctalia-shell

# Hypridle
exec-once = hypridle

# Hyprland desktop portal
#exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/xdg-desktop-portal-hyprland

# Polkit
exec-once = systemctl --user start hyprpolkitagent

# KDE connect (phone/device integration)
#exec-once = kdeconnectd

# --- Scripts ---
exec-once = ~/.config/hypr/scripts/auto_power_profiles.sh

# --- Runs on reload ---
# Laptop clamshell mode
exec = ~/.config/hypr/scripts/clamshell.sh
