# Some default windowrules for that are useful

# --- Apps ---
# nwg-look
windowrule {
    name = nwg-look
    match:class = (nwg-look)
    float = true
    center = true
    size = 700 600
}

# nwg-displays
windowrule {
    name = nwg-displays
    match:class = (nwg-displays)
    float = true
    center = true
    size = 900 600
}

# Hyprland Share Picker
windowrule {
    name = hyprland-share-picker
    match:class = (hyprland-share-picker)
    float = true
    pin = true
    center = true
    size = 600 400
}

# Picture-in-Picture
windowrule {
    name = Picture-in-Picture
    match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
    float = true
    pin = true
    center = true
}

# --- Other ---

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
